function [varargout] = importWithGivenRowCol(filename, startRow, endRow,cols)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   importWithGivenRowCol Reads data from text file FILENAME for the default
%   selection.
%
% Example:
%   [bblid,scanid,t1PostProcessExclude,ratingJB,fsFlag,fsFinalExclude] = importfile('n1601_t1QaData_v2.csv',1, 1602,[1,2,3,4,5,6]);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2017/03/06 16:46:07

%% Initialize variables.
delimiter = ',';
%% Read columns of data as strings:
% For more information, see the TEXTSCAN documentation.
nCols = max(cols);
formatSpec = '';
for i = 1:nCols
    if any(cols==i)
        formatSpec = strcat(formatSpec,'%s');
    else
        formatSpec = strcat(formatSpec,'%*s');
    end
end
formatSpec = strcat(formatSpec,'%[^\n\r]');

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric strings to numbers.
% Replace non-numeric strings with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = dataArray{col};
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=1:numel(cols)
    % Converts strings in the input cell array to numbers. Replaced non-numeric
    % strings with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1);
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData{row}, regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if any(numbers==',');
                thousandsRegExp = '^\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(numbers, thousandsRegExp, 'once'));
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric strings to numbers.
            if ~invalidThousandsSeparator;
                numbers = textscan(strrep(numbers, ',', ''), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch me
        end
    end
end


%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Allocate imported array to column variable names
if nargout ~= numel(cols)
    varargout{1} = cell(numel(cols),1);
    for i = 1:numel(cols)
        varargout{1}{i} = cell2mat(raw(:,i));
    end
    for i = 2:nargout
        varargout{i} = {};
    end
    if nargout ~= 1
        warning('Input and output sizes are not matched! All saved to the first!');
    end    
else
    for i = 1:nargout
        varargout{i} = cell2mat(raw(:,i));
    end
end










